### ISSUE TITLE
[tracking] Tests for milestone 1

### ISSUE THREAD

**Issue by sacha-l** [algorealmInc/SwarmNL#13]
## Default node setup tests:
- [x] Reading config file data works: reading bootnodes from config file
   - [x] parsing works using `util::string_to_hashmap` (it is tolerant of any bootstrap data we input)
- [x] Generating a keypair works
- [x] Generating a keypair from protobuf works
- [x] Writing keypair to config file works (`BoostrapDataParseError`)
- [x] RSA tests

## `CoreBuilder` tests:
- [x] async-std swarm builder works
    - [x] Default bootstrap config works (`TransportConfigError`, `DNSConfigError`)
    - [x] Custom TcpConfig works (`TransportConfigError`, `DNSConfigError`)
    - [x] Protocol config works (`ProtocolConfigError`)
- [x] tokio swarm builder works
    - [x] Default bootstrap config works (`TransportConfigError`, `DNSConfigError`, `ProtocolConfigError)
    - [x] Custom TcpConfig works (`TransportConfigError`, `DNSConfigError`)
    - [x] Protocol config works (`ProtocolConfigError`)
- [x] Disconnect if network id doesn't match `swarmnl/1.0`
- [x] TCP/IP and QUIC listening works (`MultiaddressListenError`)
- [x] Adding bootnodes to routing table works (`RemotePeerDialError`)
