### ISSUE TITLE
Tracking issue for adding logs

### ISSUE THREAD

**Issue by sacha-l** [algorealmInc/SwarmNL#15]
Tracking issue for the logs we want to include (non-exhaustive):
- [ ] Bootstrap nodes setup
- [ ] Transport setup 
- [ ] Node behavior and events
- [ ] On startup, with no bootnodes configured we should log that there arent any

Related: https://github.com/algorealmInc/SwarmNL/issues/7
