### ISSUE TITLE
[tracking] add documentation for milestone 1

### ISSUE THREAD

**Issue by sacha-l** [algorealmInc/SwarmNL#24]
Tracking for documenting all library source code and features for milestone 1:
- [x] remove unnecessary comments
- [x] `setup` --  add reference docs to explain node setup: how to setup a node, fallback behaviors, panics 
- [x] `core` -- see misc. But this is about building the swarm, configuring transports etc
- [x] how the application interacts with the swarm (different tasks and stream data)
- [x] node description and topics 
- [ ] implementing your own protocols

Our libraries' documentation will leverage Rustdoc features to the max, drawing inspiration from Rust libraries we like. This includes:
- using `#[doc = include_str!()]` for any API reference documentation that's not source code specific (aka most of the items listed above, using this folder structure `doc/{feature}/{doc.md}`
- using [`docify`](https://docs.rs/docify/latest/docify/) to embed examples and tests into doc comments

## Misc notes:
core builder struct
    - ip_adress defaults to ip of the machine (no need to specify)
    - Runtime struct specifies the runtimes (can be extended to use Wasm for webrtc)
    - Core Builder specifies default values
    - If we dont want default values we can explicitly provide these in the `with_network_id`
    - When you call “with_config” it has default. values. But if you want to explicity change the values, you can call the functions to do that in no particular order. You just need to make sure to call build at the very end (cant call it before calling  `with_transport`)
- confire transports: if it is default you add swam and dns etc. But we can handle a `TcpConfig::Custom` config. Then swarm is built up until the protocol and behaviour protocols.

Core builder stuff
- explain the default behavior for EventHandler and when to override it
- for example you are playing a tic tac toe game, you want to log specific things about the users joining and leaving etc. I check the number of players online, the request/response is to ask for the players high score .
- the role of this implementation override is to respond to state and instruct the network to behave in a pre-configured way. For advanced users, you need to rexeport the libp2p libraries for eventhandler 

Highlevel use of API using the Empire game example:
1. Config the builder
2. Write application specific EventHandler
