### ISSUE TITLE
[meta] Improvement on robustness of node setup

### ISSUE THREAD

**Issue by sacha-l** [algorealmInc/SwarmNL#9]
These are vairous task that we would want to tackle to improve robustness for node setup:

- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 

Misc todos:
- [x] Libp2p interfaces to re-export
- [x] Bootstrap implementations and data config
- [x] LIsten interfaces for events and interface to binaries (streams)
- [x] #12
- [x] #7
